# Generated by Django 6.1.1 on 2026-09-16 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('agent', 'Agent / Agency'), ('owner', 'Property Owner')], default='agent', max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('whatsapp_number', models.CharField(help_text='Include country code, e.g. 2348012345678 (no + or spaces).', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='A short description shown on your public profile.')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='agents/photos/')),
                ('is_verified', models.BooleanField(default=False, help_text='Set by admin after ID/CAC and address verification.')),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Free — up to 3 listings'), ('basic', 'Basic — ₦5,000/month — up to 20 listings'), ('pro', 'Pro — ₦10,000/month — unlimited + featured')], default='free', max_length=10)),
                ('plan_expires_on', models.DateField(blank=True, null=True)),
                ('is_active_subscription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
