# Generated by Django 6.1.1 on 2026-09-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free — up to 50 uploads/day'), ('basic', 'Basic — up to 150 uploads/day'), ('pro', 'Pro — unlimited + featured')], default='free', max_length=10),
        ),
    ]
