# Generated by Django 6.1.1 on 2026-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agentprofile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='account_type',
            field=models.CharField(choices=[('agent', 'Agent / Agency'), ('owner', 'Property Owner'), ('business', 'Real Estate Company')], default='agent', max_length=10),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free — up to 50 uploads/day'), ('basic', 'Basic — up to 150 uploads/day'), ('pro', 'Pro — unlimited + featured'), ('business', 'Business — unlimited + featured + business badge')], default='free', max_length=10),
        ),
    ]
