# Generated by Django 6.1.1 on 2026-09-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_seed_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(help_text='Neighbourhood / area, typed freely, e.g. "Wuse II", "Lekki Phase 1".', max_length=150),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(help_text='Type freely, e.g. "2 Bedroom Flat", "Self Contain", "Duplex", "Shop".', max_length=100),
        ),
    ]
