# Generated by Django 6.1.1 on 2026-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_area_alter_property_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(help_text="e.g. 'Ashbon Furniture', 'ABC Movers'.", max_length=150)),
                ('placement', models.CharField(choices=[('home_hero', 'Homepage — below the search bar'), ('listings_top', 'Search results — above the listings'), ('sidebar', 'Property detail page — sidebar')], max_length=20)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField(help_text="Where the ad click goes — the advertiser's site or WhatsApp link.")),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, help_text='Leave blank to start immediately.', null=True)),
                ('ends_on', models.DateField(blank=True, help_text='Leave blank to run indefinitely.', null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('rent', 'House / Apartment for Rent'), ('shortlet', 'Short-let'), ('roommate', 'Roommate / Shared Apartment'), ('office', 'Office Space'), ('land', 'Land'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('commercial', 'Other Commercial Property')], default='rent', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.CharField(blank=True, help_text='Available facilities, typed freely and separated by commas, e.g. "Water, 24hr Electricity, Parking, Security, POP Ceiling".', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_period',
            field=models.CharField(choices=[('yearly', 'Per year'), ('monthly', 'Per month'), ('weekly', 'Per week'), ('nightly', 'Per night')], default='yearly', max_length=10),
        ),
    ]
